/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mediathek.gui.bookmark;

import mediathek.tool.SVGIconUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXHyperlink;

/**
 *
 * @author Markus
 */
public class BookmarkDialogSwing extends javax.swing.JDialog {

    /**
     * Creates new form BookmarkWindow
     */
    public BookmarkDialogSwing(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        tbBookmarks = new JTable();
        toolBar = new JToolBar();
        btnDeleteEntry = new JButton();
        btnMarkViewed = new JButton();
        btnEditNote = new JButton();
        jPanel1 = new JPanel();
        btnSaveList = new JButton();
        jSeparator1 = new JToolBar.Separator();
        btnShowDetails = new JToggleButton();
        btnFilter = new JButton();
        lblCount = new JLabel();
        lblSeen = new JLabel();
        lblFilter = new JLabel();
        lblMessage = new JLabel();
        spSplitPane = new JSplitPane();
        jScrollPane2 = new JScrollPane();
        taDescription = new JTextArea();
        hyperLink = new JXHyperlink();

        jScrollPane1.setViewportView(tbBookmarks);
        if (tbBookmarks.getColumnModel().getColumnCount() > 0) {
            tbBookmarks.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbBookmarks.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbBookmarks.getColumnModel().getColumn(2).setPreferredWidth(300);
            tbBookmarks.getColumnModel().getColumn(3).setPreferredWidth(60);
            tbBookmarks.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbBookmarks.getColumnModel().getColumn(6).setPreferredWidth(25);
            tbBookmarks.getColumnModel().getColumn(7).setPreferredWidth(450);
            tbBookmarks.getColumnModel().getColumn(9).setPreferredWidth(400);
        }

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Merkliste verwalten");

        toolBar.setRollover(true);

        btnDeleteEntry.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/minus.svg"));
        btnDeleteEntry.setToolTipText("Aus der Merkliste löschen");
        btnDeleteEntry.setFocusable(false);
        btnDeleteEntry.setHorizontalTextPosition(SwingConstants.CENTER);
        btnDeleteEntry.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnDeleteEntry);

        btnMarkViewed.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/eye.svg"));
        btnMarkViewed.setFocusable(false);
        btnMarkViewed.setHorizontalTextPosition(SwingConstants.CENTER);
        btnMarkViewed.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnMarkViewed);

        btnEditNote.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/pen.svg"));
        btnEditNote.setToolTipText("Anmerkungen bearbeiten");
        btnEditNote.setFocusable(false);
        btnEditNote.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEditNote.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnEditNote);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        toolBar.add(jPanel1);

        btnSaveList.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/floppy-disk.svg"));
        btnSaveList.setToolTipText("Geänderte Merkliste abspeichern");
        btnSaveList.setFocusable(false);
        btnSaveList.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSaveList.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnSaveList);
        toolBar.add(jSeparator1);

        btnShowDetails.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/circle-info.svg"));
        btnShowDetails.setToolTipText("Erweiterte Film Informationen anzeigen");
        btnShowDetails.setFocusable(false);
        btnShowDetails.setHorizontalTextPosition(SwingConstants.CENTER);
        btnShowDetails.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnShowDetails);

        btnFilter.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/filter.svg"));
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnFilter);

        lblCount.setText("Label");

        lblSeen.setText("Label");

        lblFilter.setText("Label");

        lblMessage.setText("Label");

        spSplitPane.setDividerSize(0);
        spSplitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        spSplitPane.setRightComponent(jScrollPane2);

        hyperLink.setText("Link zur Webseite");
        hyperLink.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                hyperLinkActionPerformed(evt);
            }
        });
        spSplitPane.setBottomComponent(hyperLink);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(spSplitPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCount)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeen)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFilter)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessage)
                        .addGap(0, 458, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spSplitPane, GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCount)
                    .addComponent(lblSeen)
                    .addComponent(lblFilter)
                    .addComponent(lblMessage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hyperLinkActionPerformed(ActionEvent evt) {//GEN-FIRST:event_hyperLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hyperLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookmarkDialogSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookmarkDialogSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookmarkDialogSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookmarkDialogSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookmarkDialogSwing dialog = new BookmarkDialogSwing(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnDeleteEntry;
    public JButton btnEditNote;
    public JButton btnFilter;
    public JButton btnMarkViewed;
    public JButton btnSaveList;
    public JToggleButton btnShowDetails;
    public JXHyperlink hyperLink;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JToolBar.Separator jSeparator1;
    public JLabel lblCount;
    public JLabel lblFilter;
    public JLabel lblMessage;
    public JLabel lblSeen;
    public JSplitPane spSplitPane;
    public JTextArea taDescription;
    public JTable tbBookmarks;
    public JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
