package mediathek.gui.bookmark;

import java.awt.Frame;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import mediathek.daten.bookmark.DatenBookmark;
import mediathek.tool.SVGIconUtilities;
import mediathek.tool.listener.BeobTableHeader;
import mediathek.tool.models.TModelBookmark;
import mediathek.tool.table.MVBookmarkTable;
import org.jdesktop.swingx.JXHyperlink;

public class BookmarkDialog extends JDialog {

    /**
     * Creates new form BookmarkDialog
     */
    public BookmarkDialog(Frame parent) {
        super(parent, true);
        initComponents();
        tabelle.setModel(new TModelBookmark());
        tabelle.getTableHeader().addMouseListener(new BeobTableHeader(tabelle,
                DatenBookmark.spaltenAnzeigen,
                new int[]{DatenBookmark.BOOKMARK_ABSPIELEN, DatenBookmark.BOOKMARK_AUFZEICHNEN},
                new int[]{DatenBookmark.BOOKMARK_ABSPIELEN, DatenBookmark.BOOKMARK_AUFZEICHNEN},
                true,
                true,
                null));
    
    }


    @Override
    public void dispose() {
        tabelleSpeichern();
        super.dispose();
    }
    public void tabelleSpeichern() {
        if (tabelle != null) {
            tabelle.writeTableConfigurationData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new JToolBar();
        btnDeleteEntry = new JButton();
        btnMarkViewed = new JButton();
        btnEditNote = new JButton();
        jPanel1 = new JPanel();
        btnSaveList = new JButton();
        jSeparator1 = new JToolBar.Separator();
        btnShowDetails = new JToggleButton();
        btnFilter = new JButton();
        lblCount = new JLabel();
        lblSeen = new JLabel();
        lblFilter = new JLabel();
        lblMessage = new JLabel();
        spSplitPane = new JSplitPane();
        jScrollPane3 = new JScrollPane();
        tabelle = new MVBookmarkTable();
        jPanel2 = new JPanel();
        hyperLink = new JXHyperlink();
        jScrollPane4 = new JScrollPane();
        taDescription = new JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Merkliste verwalten");

        toolBar.setRollover(true);

        btnDeleteEntry.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/minus.svg"));
        btnDeleteEntry.setToolTipText("Aus der Merkliste löschen");
        btnDeleteEntry.setFocusable(false);
        btnDeleteEntry.setHorizontalTextPosition(SwingConstants.CENTER);
        btnDeleteEntry.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnDeleteEntry);

        btnMarkViewed.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/eye.svg"));
        btnMarkViewed.setFocusable(false);
        btnMarkViewed.setHorizontalTextPosition(SwingConstants.CENTER);
        btnMarkViewed.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnMarkViewed);

        btnEditNote.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/pen.svg"));
        btnEditNote.setToolTipText("Anmerkungen bearbeiten");
        btnEditNote.setFocusable(false);
        btnEditNote.setHorizontalTextPosition(SwingConstants.CENTER);
        btnEditNote.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnEditNote);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        toolBar.add(jPanel1);

        btnSaveList.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/floppy-disk.svg"));
        btnSaveList.setToolTipText("Geänderte Merkliste abspeichern");
        btnSaveList.setFocusable(false);
        btnSaveList.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSaveList.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnSaveList);
        toolBar.add(jSeparator1);

        btnShowDetails.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/circle-info.svg"));
        btnShowDetails.setToolTipText("Erweiterte Film Informationen anzeigen");
        btnShowDetails.setFocusable(false);
        btnShowDetails.setHorizontalTextPosition(SwingConstants.CENTER);
        btnShowDetails.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnShowDetails);

        btnFilter.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/filter.svg"));
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(SwingConstants.BOTTOM);
        toolBar.add(btnFilter);

        lblCount.setText("Label");

        lblSeen.setText("Label");

        lblFilter.setText("Label");

        lblMessage.setText("Label");

        spSplitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);

        jScrollPane3.setViewportView(tabelle);

        spSplitPane.setLeftComponent(jScrollPane3);

        hyperLink.setText("Link zur Webseite");

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane4.setViewportView(taDescription);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hyperLink, GroupLayout.PREFERRED_SIZE, 845, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(364, 364, 364)
                    .addComponent(hyperLink, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        spSplitPane.setRightComponent(jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(spSplitPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCount)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeen)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFilter)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessage)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSplitPane)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCount)
                    .addComponent(lblSeen)
                    .addComponent(lblFilter)
                    .addComponent(lblMessage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnDeleteEntry;
    public JButton btnEditNote;
    public JButton btnFilter;
    public JButton btnMarkViewed;
    public JButton btnSaveList;
    public JToggleButton btnShowDetails;
    public JXHyperlink hyperLink;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JToolBar.Separator jSeparator1;
    public JLabel lblCount;
    public JLabel lblFilter;
    public JLabel lblMessage;
    public JLabel lblSeen;
    public JSplitPane spSplitPane;
    public JTextArea taDescription;
    public MVBookmarkTable tabelle;
    public JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
