/*    
 *    MediathekView
 *    Copyright (C) 2008   W. Xaver
 *    W.Xaver[at]googlemail.com
 *    http://zdfmediathk.sourceforge.net/
 *    
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package mediathek.gui.dialog;

import javafx.application.Platform;
import javafx.scene.control.Alert;
import mSearch.daten.DatenFilm;
import mediathek.config.Icons;
import mediathek.config.Konstanten;
import mediathek.tool.EscapeKeyHandler;
import mediathek.tool.MVInfoFile;
import net.miginfocom.layout.AC;
import net.miginfocom.layout.CC;
import net.miginfocom.layout.LC;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;

@SuppressWarnings("serial")
public class DialogFilmBeschreibung extends JDialog {
    private static final String TITLE = "Beschreibung ändern";

    public DialogFilmBeschreibung(JFrame parent, DatenFilm datenFilm) {
        super(parent, true);

        initComponents();

        setTitle(TITLE);
        if (parent != null)
            setLocationRelativeTo(parent);

        EscapeKeyHandler.installHandler(this, this::dispose);

        jTextArea1.setText(datenFilm.getDescription());
        jTextFieldTitel.setText(datenFilm.getTitle());

        jButtonOk.addActionListener(e -> {
            datenFilm.setDescription(jTextArea1.getText());
            dispose();
        });

        jButtonHilfe.setIcon(Icons.ICON_BUTTON_HELP);
        jButtonHilfe.addActionListener(e -> Platform.runLater(() -> {
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setTitle(Konstanten.PROGRAMMNAME);
            alert.setHeaderText("Hilfe zu " + TITLE);
            alert.setContentText("Diese Funktion richtet sich z.B. an Benutzer,"
                    + "welche eine angepasste Beschreibung der Sendung in Form "
                    + "der Infodatei (\"Filmname.txt\") anlegen "
                    + "und durch Drittprogramme einlesen lassen wollen.\n\n"
                    + "Achtung: Diese Änderungen gehen nach dem Neuladen "
                    + "einer Filmliste verloren.");
            alert.showAndWait();

        }));

        jButtonSpeichern.addActionListener(e -> {
            datenFilm.setDescription(jTextArea1.getText());
            MVInfoFile file = new MVInfoFile();
            file.writeInfoFile(datenFilm);
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        var panel1 = new JPanel();
        jButtonOk = new JButton();
        jButtonHilfe = new JButton();
        jButtonSpeichern = new JButton();
        var jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        var panel2 = new JPanel();
        var jLabel2 = new JLabel();
        jTextFieldTitel = new JTextField();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        var contentPane = getContentPane();
        contentPane.setLayout(new MigLayout(
            new LC().fill().insets("5").hideMode(3).gridGap("5", "5"), //NON-NLS
            // columns
            new AC()
                .grow().fill(),
            // rows
            new AC()
                .fill().gap()
                .grow().fill().gap()
                .fill()));

        //======== panel1 ========
        {
            panel1.setLayout(new MigLayout(
                new LC().insets("0").hideMode(3).gridGap("5", "5"), //NON-NLS
                // columns
                new AC()
                    .fill().gap()
                    .grow().fill().gap()
                    .fill().gap()
                    .fill(),
                // rows
                new AC()
                    .fill()));

            //---- jButtonOk ----
            jButtonOk.setText("Ok"); //NON-NLS
            panel1.add(jButtonOk, new CC().cell(3, 0));

            //---- jButtonHilfe ----
            jButtonHilfe.setIcon(new ImageIcon(getClass().getResource("/mediathek/res/muster/button-help.png"))); //NON-NLS
            jButtonHilfe.setToolTipText("Hilfe anzeigen"); //NON-NLS
            panel1.add(jButtonHilfe, new CC().cell(2, 0));

            //---- jButtonSpeichern ----
            jButtonSpeichern.setText("Speichern"); //NON-NLS
            panel1.add(jButtonSpeichern, new CC().cell(0, 0));
        }
        contentPane.add(panel1, new CC().cell(0, 2));

        //======== jScrollPane1 ========
        {

            //---- jTextArea1 ----
            jTextArea1.setColumns(20);
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(5);
            jTextArea1.setWrapStyleWord(true);
            jScrollPane1.setViewportView(jTextArea1);
        }
        contentPane.add(jScrollPane1, new CC().cell(0, 1));

        //======== panel2 ========
        {
            panel2.setLayout(new MigLayout(
                new LC().insets("0").hideMode(3).gridGap("5", "5"), //NON-NLS
                // columns
                new AC()
                    .fill().gap()
                    .grow().fill(),
                // rows
                new AC()
                    .fill()));

            //---- jLabel2 ----
            jLabel2.setText("Filmtitel:"); //NON-NLS
            panel2.add(jLabel2, new CC().cell(0, 0));

            //---- jTextFieldTitel ----
            jTextFieldTitel.setEditable(false);
            panel2.add(jTextFieldTitel, new CC().cell(1, 0));
        }
        contentPane.add(panel2, new CC().cell(0, 0));
        setSize(490, 185);
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    private JButton jButtonOk;
    private JButton jButtonHilfe;
    private JButton jButtonSpeichern;
    private JTextArea jTextArea1;
    private JTextField jTextFieldTitel;
    // End of variables declaration//GEN-END:variables

}
