package mediathek.javaswing.filterpanel;

import java.awt.Component;
import mediathek.tool.FilterDTO;
import mediathek.tool.SVGIconUtilities;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;


public class CommonViewSettingsPaneSwing extends JDialog {

    public CommonViewSettingsPaneSwing(Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterSelect = new JComboBox<>();
        btnRenameFilter = new JButton();
        btnaddNewFilter = new JButton();
        btnDeleteCurrentFilter = new JButton();
        btnDeleteFilterSettings = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter");

        btnRenameFilter.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/pen-to-square.svg"));
        btnRenameFilter.setToolTipText("Filter umbenennen");
        btnRenameFilter.setPreferredSize(new Dimension(72, 22));

        btnaddNewFilter.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/plus.svg"));
        btnaddNewFilter.setToolTipText("Neuen Filter anlegen");
        btnaddNewFilter.setPreferredSize(new Dimension(72, 22));

        btnDeleteCurrentFilter.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/trash-can.svg"));
        btnDeleteCurrentFilter.setToolTipText("Aktuellen Filter löschen");
        btnDeleteCurrentFilter.setPreferredSize(new Dimension(72, 22));

        btnDeleteFilterSettings.setIcon(SVGIconUtilities.createSVGIcon("icons/fontawesome/recycle.svg"));
        btnDeleteFilterSettings.setToolTipText("Aktuellen Filter zurücksetzen");
        btnDeleteFilterSettings.setPreferredSize(new Dimension(72, 22));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterSelect, 0, 202, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRenameFilter, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaddNewFilter, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteCurrentFilter, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteFilterSettings, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {btnDeleteCurrentFilter, btnDeleteFilterSettings, btnRenameFilter, btnaddNewFilter});

        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteFilterSettings, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddNewFilter, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenameFilter, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterSelect, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCurrentFilter, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(604, Short.MAX_VALUE))
        );

        layout.linkSize(SwingConstants.VERTICAL, new Component[] {btnDeleteCurrentFilter, btnDeleteFilterSettings, btnRenameFilter, btnaddNewFilter});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton btnDeleteCurrentFilter;
    public JButton btnDeleteFilterSettings;
    public JButton btnRenameFilter;
    public JButton btnaddNewFilter;
    public JComboBox<FilterDTO> filterSelect;
    // End of variables declaration//GEN-END:variables
}
