package mediathek.gui.dialogEinstellungen;

import mediathek.tool.EscapeKeyHandler;
import net.miginfocom.layout.AC;
import net.miginfocom.layout.CC;
import net.miginfocom.layout.LC;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;

@SuppressWarnings("serial")
public class DialogFarbe extends JDialog {
    public Color farbe;

    public DialogFarbe(JFrame parent, Color color) {
        super(parent, true);
        initComponents();
        if (color != null) {
            jColorChooser.setColor(color);
        }

        jColorChooser.getSelectionModel().addChangeListener(e -> farbe = jColorChooser.getColor());
        jButtonOk.addActionListener(l -> dispose());
        jButtonAbbrechen.addActionListener(l -> abbrechen());

        EscapeKeyHandler.installHandler(this, this::abbrechen);
    }

    private void abbrechen() {
        farbe = null;
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        jColorChooser = new JColorChooser();
        var panel1 = new JPanel();
        jButtonAbbrechen = new JButton();
        jButtonOk = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Farbe ausw\u00e4hlen"); //NON-NLS
        var contentPane = getContentPane();
        contentPane.setLayout(new MigLayout(
            new LC().insets("5").hideMode(3).gridGap("5", "5"), //NON-NLS
            // columns
            new AC()
                .fill(),
            // rows
            new AC()
                .fill().gap()
                .fill()));
        contentPane.add(jColorChooser, new CC().cell(0, 0));

        //======== panel1 ========
        {
            panel1.setLayout(new MigLayout(
                new LC().insets("0").hideMode(3).gridGap("5", "5"), //NON-NLS
                // columns
                new AC()
                    .fill().gap()
                    .fill(),
                // rows
                new AC()
                    .fill()));

            //---- jButtonAbbrechen ----
            jButtonAbbrechen.setText("Abbrechen"); //NON-NLS
            panel1.add(jButtonAbbrechen, new CC().cell(1, 0));

            //---- jButtonOk ----
            jButtonOk.setText("OK"); //NON-NLS
            panel1.add(jButtonOk, new CC().cell(0, 0));
        }
        contentPane.add(panel1, new CC().cell(0, 1).alignX("right").growX(0)); //NON-NLS
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    private JColorChooser jColorChooser;
    private JButton jButtonAbbrechen;
    private JButton jButtonOk;
    // End of variables declaration//GEN-END:variables
}
