package mediathek.gui.dialogEinstellungen;

import javax.swing.*;
import java.awt.*;

public class DialogImportPsetBase extends JDialog {

    public DialogImportPsetBase(
            JFrame parent,
            boolean modal
    ) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        jCheckBoxAlleEinstellungen = new JCheckBox();
        jButtonOk = new JButton();
        jButtonAbbrechen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        var contentPane = getContentPane();

        //---- jCheckBoxAlleEinstellungen ----
        jCheckBoxAlleEinstellungen.setText("alle Einstellungen anzeigen");

        //---- jButtonOk ----
        jButtonOk.setText("Ok");

        //---- jButtonAbbrechen ----
        jButtonAbbrechen.setText("Abbrechen");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jCheckBoxAlleEinstellungen)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                            .addComponent(jButtonOk, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAbbrechen)))
                    .addContainerGap())
        );
        contentPaneLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jButtonAbbrechen, jButtonOk});
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxAlleEinstellungen)
                        .addComponent(jButtonAbbrechen)
                        .addComponent(jButtonOk))
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    protected JScrollPane jScrollPane1;
    protected JCheckBox jCheckBoxAlleEinstellungen;
    protected JButton jButtonOk;
    protected JButton jButtonAbbrechen;
    // End of variables declaration//GEN-END:variables
}
