package mediathek.gui.dialogEinstellungen;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class PanelProgrammPfadeBase extends JPanel {
    public PanelProgrammPfadeBase() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        var jScrollPane1 = new JScrollPane();
        var jPanel1 = new JPanel();
        jPanelVlc = new JPanel();
        jTextFieldVlc = new JTextField();
        jButtonVlcPfad = new JButton();
        jButtonVlcSuchen = new JButton();
        jButtonHilfe = new JButton();
        jPanelFFmpeg = new JPanel();
        jTextFieldFFmpeg = new JTextField();
        jButtonFFmpegSuchen = new JButton();
        jButtonFFmpegPfad = new JButton();

        //======== this ========

        //======== jScrollPane1 ========
        {

            //======== jPanel1 ========
            {

                //======== jPanelVlc ========
                {
                    jPanelVlc.setBorder(new TitledBorder("Pfad zum VLC-Player ausw\u00e4hlen"));

                    //---- jButtonVlcPfad ----
                    jButtonVlcPfad.setIcon(new ImageIcon(getClass().getResource("/mediathek/res/muster/button-file-open.png")));
                    jButtonVlcPfad.setToolTipText("Programm ausw\u00e4hlen");

                    //---- jButtonVlcSuchen ----
                    jButtonVlcSuchen.setText("suchen");
                    jButtonVlcSuchen.setToolTipText("nach dem Programm suchen");

                    GroupLayout jPanelVlcLayout = new GroupLayout(jPanelVlc);
                    jPanelVlc.setLayout(jPanelVlcLayout);
                    jPanelVlcLayout.setHorizontalGroup(
                        jPanelVlcLayout.createParallelGroup()
                            .addGroup(jPanelVlcLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldVlc)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVlcPfad)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVlcSuchen)
                                .addContainerGap())
                    );
                    jPanelVlcLayout.setVerticalGroup(
                        jPanelVlcLayout.createParallelGroup()
                            .addGroup(jPanelVlcLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelVlcLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextFieldVlc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonVlcPfad)
                                    .addComponent(jButtonVlcSuchen))
                                .addContainerGap())
                    );
                    jPanelVlcLayout.linkSize(SwingConstants.VERTICAL, new Component[] {jButtonVlcPfad, jTextFieldVlc});
                }

                //---- jButtonHilfe ----
                jButtonHilfe.setIcon(new ImageIcon(getClass().getResource("/mediathek/res/muster/button-help.png")));
                jButtonHilfe.setToolTipText("Hilfe anzeigen");

                //======== jPanelFFmpeg ========
                {
                    jPanelFFmpeg.setBorder(new TitledBorder("Pfad zu ffmpeg ausw\u00e4hlen"));

                    //---- jButtonFFmpegSuchen ----
                    jButtonFFmpegSuchen.setText("suchen");
                    jButtonFFmpegSuchen.setToolTipText("nach dem Programm suchen");

                    //---- jButtonFFmpegPfad ----
                    jButtonFFmpegPfad.setIcon(new ImageIcon(getClass().getResource("/mediathek/res/muster/button-file-open.png")));
                    jButtonFFmpegPfad.setToolTipText("Programm ausw\u00e4hlen");

                    GroupLayout jPanelFFmpegLayout = new GroupLayout(jPanelFFmpeg);
                    jPanelFFmpeg.setLayout(jPanelFFmpegLayout);
                    jPanelFFmpegLayout.setHorizontalGroup(
                        jPanelFFmpegLayout.createParallelGroup()
                            .addGroup(jPanelFFmpegLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldFFmpeg, GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFFmpegPfad)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFFmpegSuchen)
                                .addContainerGap())
                    );
                    jPanelFFmpegLayout.setVerticalGroup(
                        jPanelFFmpegLayout.createParallelGroup()
                            .addGroup(jPanelFFmpegLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelFFmpegLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextFieldFFmpeg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonFFmpegPfad)
                                    .addComponent(jButtonFFmpegSuchen))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    jPanelFFmpegLayout.linkSize(SwingConstants.VERTICAL, new Component[] {jButtonFFmpegPfad, jButtonFFmpegSuchen, jTextFieldFFmpeg});
                }

                GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup()
                                .addComponent(jPanelVlc, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonHilfe))
                                .addComponent(jPanelFFmpeg, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup()
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanelVlc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelFFmpeg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonHilfe)
                            .addContainerGap(84, Short.MAX_VALUE))
                );
            }
            jScrollPane1.setViewportView(jPanel1);
        }

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    protected JPanel jPanelVlc;
    protected JTextField jTextFieldVlc;
    protected JButton jButtonVlcPfad;
    protected JButton jButtonVlcSuchen;
    protected JButton jButtonHilfe;
    protected JPanel jPanelFFmpeg;
    protected JTextField jTextFieldFFmpeg;
    protected JButton jButtonFFmpegSuchen;
    protected JButton jButtonFFmpegPfad;
    // End of variables declaration//GEN-END:variables
}
