/*
 * Copyright (c) 2026 derreisende77.
 * This code was developed as part of the MediathekView project https://github.com/mediathekview/MediathekView
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package mediathek.gui.dialog.edit_download;

import net.miginfocom.layout.AC;
import net.miginfocom.layout.CC;
import net.miginfocom.layout.LC;
import net.miginfocom.swing.MigLayout;
import org.jdesktop.swingx.JXBusyLabel;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DialogEditDownloadView extends JDialog {
    protected DialogEditDownloadView(Frame owner) {
        super(owner);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        var jScrollPane1 = new JScrollPane();
        jPanelExtra = new ViewportWidthPanel();
        jPanelRes = new JPanel();
        var jPanelResButtons = new JPanel();
        jRadioButtonResHd = new JRadioButton();
        jRadioButtonResHi = new JRadioButton();
        jRadioButtonResLo = new JRadioButton();
        var jPanelResInfo = new JPanel();
        jButtonRequestLiveInfo = new JButton();
        jLabelBusyIndicator = new JXBusyLabel();
        var jPanelLiveInfo = new JPanel();
        jLabelVideoInfo = new JLabel();
        jLabelAudioInfo = new JLabel();
        var buttonPanel = new JPanel();
        jButtonOk = new JButton();
        jButtonAbbrechen = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download \u00e4ndern");
        setMinimumSize(new Dimension(720, 500));
        setModal(true);
        setPreferredSize(null);
        var contentPane = getContentPane();
        contentPane.setLayout(new MigLayout(
            new LC().insets("panel").hideMode(3).gridGap("0", "11"),
            // columns
            new AC()
                .grow().fill(),
            // rows
            new AC()
                .grow().fill().gap()
                .fill().gap()
                .fill()));

        //======== jScrollPane1 ========
        {
            jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

            //======== jPanelExtra ========
            {
                jPanelExtra.setLayout(new MigLayout(
                    new LC().fillX().insets("5").hideMode(3),
                    // columns
                    new AC()
                        .align("right").gap()
                        .grow().fill(),
                    // rows
                    new AC()
                        ));
            }
            jScrollPane1.setViewportView(jPanelExtra);
        }
        contentPane.add(jScrollPane1, new CC().cell(0, 0).grow());

        //======== jPanelRes ========
        {
            jPanelRes.setBorder(new TitledBorder("Download-Qualit\u00e4t:"));
            jPanelRes.setLayout(new MigLayout(
                new LC().fillX().insets("5").hideMode(3),
                // columns
                new AC()
                    .grow().fill(),
                // rows
                new AC()
                    .fill().gap()
                    .fill()));

            //======== jPanelResButtons ========
            {
                jPanelResButtons.setLayout(new MigLayout(
                    new LC().insets("0").hideMode(3).alignX("left").gridGap("20", "0"),
                    // columns
                    new AC()
                        .size("pref!").gap()
                        .size("pref!").gap()
                        .size("pref!"),
                    // rows
                    new AC()
                        .fill()));

                //---- jRadioButtonResHd ----
                jRadioButtonResHd.setText("H\u00f6chste/Hoch");
                jPanelResButtons.add(jRadioButtonResHd, new CC().cell(0, 0));

                //---- jRadioButtonResHi ----
                jRadioButtonResHi.setText("Mittel");
                jPanelResButtons.add(jRadioButtonResHi, new CC().cell(1, 0));

                //---- jRadioButtonResLo ----
                jRadioButtonResLo.setText("Niedrig");
                jPanelResButtons.add(jRadioButtonResLo, new CC().cell(2, 0));
            }
            jPanelRes.add(jPanelResButtons, new CC().cell(0, 0).alignX("left"));

            //======== jPanelResInfo ========
            {
                jPanelResInfo.setLayout(new MigLayout(
                    new LC().fillX().insets("0").hideMode(3).gridGap("10", "0"),
                    // columns
                    new AC()
                        .size("pref!").gap()
                        .size("pref!").gap()
                        .grow().fill(),
                    // rows
                    new AC()
                        .fill()));

                //---- jButtonRequestLiveInfo ----
                jButtonRequestLiveInfo.setText("Codec-Details abrufen...");
                jPanelResInfo.add(jButtonRequestLiveInfo, new CC().cell(0, 0).alignY("top"));
                jPanelResInfo.add(jLabelBusyIndicator, new CC().cell(1, 0).alignY("top"));

                //======== jPanelLiveInfo ========
                {
                    jPanelLiveInfo.setLayout(new GridLayout(2, 1));

                    //---- jLabelVideoInfo ----
                    jLabelVideoInfo.setText("Video: n/a");
                    jPanelLiveInfo.add(jLabelVideoInfo);

                    //---- jLabelAudioInfo ----
                    jLabelAudioInfo.setText("Audio: n/a");
                    jPanelLiveInfo.add(jLabelAudioInfo);
                }
                jPanelResInfo.add(jPanelLiveInfo, new CC().cell(2, 0).pushX().growX());
            }
            jPanelRes.add(jPanelResInfo, new CC().cell(0, 1).growX());
        }
        contentPane.add(jPanelRes, new CC().cell(0, 1).growX());

        //======== buttonPanel ========
        {
            buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 0));

            //---- jButtonOk ----
            jButtonOk.setText("Ok");
            buttonPanel.add(jButtonOk);

            //---- jButtonAbbrechen ----
            jButtonAbbrechen.setText("Abbrechen");
            buttonPanel.add(jButtonAbbrechen);
        }
        contentPane.add(buttonPanel, new CC().cell(0, 2).growX());
        pack();
        setLocationRelativeTo(getOwner());

        //---- buttonGroup1 ----
        var buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(jRadioButtonResHd);
        buttonGroup1.add(jRadioButtonResHi);
        buttonGroup1.add(jRadioButtonResLo);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    protected ViewportWidthPanel jPanelExtra;
    protected JPanel jPanelRes;
    protected JRadioButton jRadioButtonResHd;
    protected JRadioButton jRadioButtonResHi;
    protected JRadioButton jRadioButtonResLo;
    protected JButton jButtonRequestLiveInfo;
    protected JXBusyLabel jLabelBusyIndicator;
    protected JLabel jLabelVideoInfo;
    protected JLabel jLabelAudioInfo;
    protected JButton jButtonOk;
    protected JButton jButtonAbbrechen;
    // End of variables declaration//GEN-END:variables
}
